// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	Characterid        int32
	Characterownerhash string
	Expiry             pgtype.Timestamptz
	Portraiturl        string
	Name               string
}

type Event struct {
	Eventid     int32
	Characterid int32
	Date        pgtype.Date
	Duration    string
	Ownername   string
	Ownertype   string
	Response    string
	Text        string
	Title       string
}

type Scope struct {
	Scopeid int32
	Data    []byte
	Expiry  pgtype.Timestamptz
}

type Token struct {
	Tokenid      int32
	Characterid  int32
	AccessToken  string
	TokenType    string
	RefreshToken string
	Expiry       pgtype.Timestamptz
}

type User struct {
	Userid             int32
	Characterownerhash string
}
